### ISSUE TITLE
New plugin for depth camera simulation

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#100]
As originally discussed in https://github.com/robotology/gazebo_yarp_plugins/issues/96#issue-33786569 , there is an interest in properly exposing simulated depth cameras using yarp devices. 

Most of the glue code for reading the sdf, setting/getting the sensor pointer from the singleton can be adapted from an existing plugin, for example the `gazebo_yarp_forcetorque`, in the following files:
- https://github.com/robotology/gazebo_yarp_plugins/blob/master/src/gazebo_plugins/ForceTorque.cc
- https://github.com/robotology/gazebo_yarp_plugins/blob/master/src/yarp_drivers/ForceTorqueDriver.cpp

The depth camera is properly defined as sensor in Gazebo, and documentation is available:
- Depth camera: http://gazebosim.org/api/dev/classgazebo_1_1sensors_1_1DepthCameraSensor.html

A good example of use of the `DepthCameraSensor` class is available in the relative ROS plugins, available in the `gazebo_ros_pkgs` software: https://github.com/ros-simulation/gazebo_ros_pkgs/tree/hydro-devel/gazebo_plugins/src .

I am not an expert in how depth camera are encapsulated using yarp driver interfaces, but apparently a kinect-related [yarp driver interface](http://wiki.icub.org/yarpdoc/classyarp_1_1dev_1_1KinectDeviceDriver.html) and [wrapper](http://wiki.icub.org/yarpdoc/classyarp_1_1dev_1_1KinectDeviceDriverServer.html) are available in Yarp.
Furthermore openni-related [driver](http://wiki.icub.org/yarpdoc/classyarp_1_1dev_1_1IOpenNI2DeviceDriver.html) and [wrapper](http://wiki.icub.org/yarpdoc/classyarp_1_1dev_1_1OpenNI2DeviceDriverServer.html) are also available.

**Comment by barbalberto** [comment]
I'll start working on this in the next days/weeks

**Comment by barbalberto** [comment]
I'm working on this plugin. I faced the problem that there is no standard in YARP for depth camera data, nor for kinect-like one.
An internal meeting will be help on monday 23/11/15 afternoon to define one to let this tak continue and schedule the refactoring of kinect-like yarp devices for the long-run.

Discussion about standard will be hosted here: https://github.com/robotology/yarp/issues/643
while this thread will follows the Gazebo specific implemetation

**Comment by barbalberto** [comment]
Plugin and grabber are done with very basic featires in a branches: 
YARP: depthSensor
gazeboYarpPlugin: depthCameraPlugin

working on yarp client

**Comment by barbalberto** [comment]
depthCamera wrapper and client are merged in master.
Streaming of data is ok, RPC calls are yet not implemented.

**Comment by traversaro** [comment]
@barbalberto can we close this issue? Or there is still something going on?

**Comment by barbalberto** [comment]
Plugin is done, I forgot to close the issue.
