### ISSUE TITLE
New plugin for laser scanner simulation

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#101]
As originally discussed in https://github.com/robotology/gazebo_yarp_plugins/issues/96#issue-33786569 , there is an interest in properly exposing simulated laser scanner using yarp devices. 

Most of the glue code for reading the sdf, setting/getting the sensor pointer from the singleton can be adapted from an existing plugin, for example the `gazebo_yarp_forcetorque`, in the following files:
* https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/forcetorque/src/ForceTorque.cc
* https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/forcetorque/src/ForceTorqueDriver.cpp

The laser scanner is properly defined as sensor in Gazebo, and documentation is available:
* Laser : https://osrf-distributions.s3.amazonaws.com/gazebo/api/dev/classgazebo_1_1sensors_1_1RaySensor.html

A good example of use of the `RaySensor` class is available in the relative ROS plugins, available in the `gazebo_ros_pkgs` software: https://github.com/ros-simulation/gazebo_ros_pkgs/tree/hydro-devel/gazebo_plugins/src .

Apparently no laser scanner device interface is available in Yarp. However the [iKart](http://wiki.icub.org/wiki/IKart) (a mobile wheeled base for the iCub robot) already publishes laser scan data on a Yarp port.

**Comment by traversaro** [comment]
Apparently a Laser sensors interface have been recently added in YARP by @randaz81 : https://github.com/robotology/yarp/pull/656 .

**Comment by randaz81** [comment]
implementation 100% completed
