### ISSUE TITLE
position PID configuration parameters cleanup

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#119]
@andreadelprete is having trouble while tuning the position PID gains of the iCub . 
Apparently is not clearly documented the meaning of the PID gains.
I am currently checking in the code, but we should document it somewhere.

**Comment by traversaro** [comment]
Interestingly, for some reason commit https://github.com/robotology/gazebo-yarp-plugins/commit/4cf6b341068e33d5187501b1f95d4d94cfef20bc (that was fundamental to fix antiwindup terms and general limit of the controller) never made it to master...

**Comment by barbalberto** [comment]
How is the state of this issue? Can be closed?

**Comment by traversaro** [comment]
No. The pid format is still not documented, and additionally we should migrate to specifying them in degrees-based units, to be consistent with the rest of the interface.

**Comment by traversaro** [comment]
Furthermore, the velocity PID interfaces are not properly accounting for the unit of measurement mismatch.

**Comment by randaz81** [comment]
@traversaro As mentioned in #218, various changes were recently done to the PID parameters. 
Is this issue still open?

**Comment by traversaro** [comment]
I think we can consider this issue as solved.
