### ISSUE TITLE
gazebo-yarp-plugins use with roslaunch

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#123]
Hi ROS and gazebo-yarp-plugins users @EnricoMingo @arocchi @MirkoFerrati, we have a question for you. 
Here at the iCub summer school @miaragao is working in integration the `gazebo_yarp_controlboard` plugin in its Vizzy robot simulation. 
He is launching the simulation using roslaunch as described in the [gazebo ros documentation](http://gazebosim.org/wiki/Tutorials/1.9/Using_roslaunch_Files_to_Spawn_Models), and apparently the `GAZEBO_PLUGIN_PATH` does not contains the directory in which the gazebo-yarp-plugins are found, even if the 
~~~
export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:/path/to/gazebo-yarp-plugins/build
~~~
iine in `.bashrc` is correctly set. Apparently roslaunch is overwriting at some point the `GAZEBO_PLUGIN_PATH` environment variable. 
Have you every experienced something similar, and you know a clean solution to this problem?
Thanks

**Comment by traversaro** [comment]
This should be fixed by Gazebo PR https://bitbucket.org/osrf/gazebo/pull-request/1430/preserve-previous-gazebo_model_path-values/diff , as explained in https://bitbucket.org/osrf/gazebo_tutorials/issue/27/roslaunch-not-working-properly-when-using .

**Comment by traversaro** [comment]
This bug should be solved by https://bitbucket.org/osrf/gazebo/pull-request/1430/preserve-previous-gazebo_model_path-values/diff (thanks @scpeters!) in Gazebo 4.1 , and I guess it will be propagated to following versions. 

@mikearagao  feel free to re-open if the problem persists , or if we need to solve this even for Gazebo versions older then 4.1 .

**Comment by scpeters** [comment]
I merged it forward to gazebo5 and the default branch, though it hasn't been released in any debian packages yet.
