### ISSUE TITLE
Crash "gazebo.msgs.PosesStamped missing fields: time.sec, time.nsec"

### ISSUE THREAD

**Issue by andreadelprete** [robotology/gazebo-yarp-plugins#125]
Gazebo crashes with the following message:
```
libprotobuf FATAL google/protobuf/message_lite.cc:273] CHECK failed: IsInitialized(): Can't serialize message of type "gazebo.msgs.PosesStamped" because it is missing required fields: time.sec, time.nsec
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: IsInitialized(): Can't serialize message of type "gazebo.msgs.PosesStamped" because it is missing required fields: time.sec, time.nsec
Aborted (core dumped)
```
The crash happens when starting to interact with the robot (iCub feet fixed), sometimes as soon as a robotMotorGui is opened, other times after some minutes of work, but it does not seem associated to a particular event.

I'm using the latest version of yarp and gazebo_yarp_plugins.

**Comment by traversaro** [comment]
It was probably fixed long ago, hopefully.
