### ISSUE TITLE
iCub not loading properly in Gazebo using simbody

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/gazebo-yarp-plugins#126]
Hello,

we are trying different engines in Gazebo v.4.
We launched gazebo with simbody:
gazebo -e simbody
and this is what happens when we drag and drop iCub inside the world: iCub (fixed, normal or fixed feet) is crashed in pieces to the floor, only the root element remains in the air. iCub Legs, instead, make Gazebo crash.
This problem does not happen with other physics engines (ODE, Bullet). We don't know for DARTS since it is not included in the debain version. This can be seen here:

$ ldd `which gzserver` | grep libgazebo_physics
	libgazebo_physics.so.4 => /usr/lib/x86_64-linux-gnu/libgazebo_physics.so.4 (0x00007ff731fda000)
	libgazebo_physics_ode.so.4 => /usr/lib/x86_64-linux-gnu/libgazebo_physics_ode.so.4 (0x00007ff72d136000)
	libgazebo_physics_bullet.so.4 => /usr/lib/x86_64-linux-gnu/libgazebo_physics_bullet.so.4 (0x00007ff72cea6000)
	libgazebo_physics_simbody.so.4 => /usr/lib/x86_64-linux-gnu/libgazebo_physics_simbody.so.4 (0x00007ff72cc1d000)

**Comment by traversaro** [comment]
Thanks to the new fixed joint support added in Gazebo6 this issue should be solved. Please test the icub model in https://github.com/robotology-playground/icub-gazebo/tree/gazebo6 to run iCub in simbody.
