### ISSUE TITLE
[controlboard] Torque control error

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#155]
Originally reported by Rajesh Subburaman on Walkman project internal bug tracker:

> Hi, I have been working on a controller which uses torque mode control to manipulate the coman robot. I am working only with the robot model using  the gazebo simulator.  I am facing a strange problem, i compute the desired torque and set it as reference, but the torque which is applied/sensed doesn't match with the reference values. This doesn't happen for all the joints, it occurs randomly to some joints. The following are the strange things which i noticed so far. 1. For -ve torque reference, +ve torque is applied (rarely) 2. Irrespective of the torque value, sometimes it applies 0 Nm for some joints. 3. This mismatch starts with 1 or 2 joints and it increases randomly to other joints as the iteration progresses.
>
> It would be great if someone can help us in fixing this problem.

**Comment by DanielePucci** [comment]
Closing. Ready to re-open it in the case it is needed.
