### ISSUE TITLE
Stop using Gazebo JointController in the ControlBoard plugin

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#165]
And directly uset setForce()/addForce methods in the controlboard plugin.

Currently the low level position and velocity PIDs are updated at every Gazebo [WorldUpdateBegin](https://github.com/robotology/gazebo-yarp-plugins/blob/master/src/yarp_drivers/ControlBoardDriver.cpp#L89) event by sending references to the Gazebo JointController through the Gazebo protobuf internal middleware (see `sendPositionToGazebo`, `sendVelocityToGazebo`and `sendTorqueToGazebo` methods). This messages are then received by the Gazebo internal [JointController](https://bitbucket.org/osrf/gazebo/src/7d2654784d9e7fba7088e6837155f4982fb6a3d3/gazebo/physics/JointController.cc?at=default#cl-154). This messages are then used in the `JointController::Update()` method, that is itself called by the main gazebo physics thread update method, and use the `Joint::SetForce` method to actually apply torque to the joints. 
I always found this disturbing for two reasons:
- We basically have a function (our plugin `onUpdate`) that is called my the physics thread, that sends some data to the physics thread itself  through an external middleware. This is both ugly and inefficient. 
- We are bound to use internal Gazebo PID structure as a black box, while for example for supporting Mixed Position-Velocity control or Coupled DOFs we would prefer to have full control of the control loop. 

For this reason, the first step could be to move the control logic completely in the `gazebo_yarp_controlboard`, by calling the `SetForce` in the `OnUpdate` method. This can be simplified by using the same `gazebo::common::PID` object already used in the JointController. 
Once we have complete control of the control loop, we can easily program any kind of behaviour actually implemented in the low level firmware, such as coupled mechanism control.

Discussing starting from here: https://github.com/robotology/gazebo-yarp-plugins/commit/5c2173f0362a1c598ba958baddaefe032955d834 , the rationale behind this issue was discussed here: 
https://github.com/robotology/gazebo-yarp-plugins/issues/149 .

**Comment by mikearagao** [comment]
Hi @traversaro, I'm back on this, do you know if someone already tried to run my last commit with the iCub?

Cheers!

**Comment by traversaro** [comment]
Ok @mikearagao , if you think it should work as master we can test it!

**Comment by mikearagao** [comment]
I will try to run it with the iCub before merge. I will try to do this later on the afternoon, I'll keep you updated!

**Comment by traversaro** [comment]
Ok! Furthermore both we and the coman guys have a walking demo working in gazebo, we will test that one for verifying that everything is properly working before merging. 
(We are also setting up a infrastructure for unit testing devices and robots: https://github.com/robotology/robot-testing , this would be the perfect use case).

**Comment by mikearagao** [comment]
@traversaro, sorry for the late response.

Have been working on Vizzy locomotion, but I wanted to ask you to run that demo with the iCub if possible. I was having some issues running the iCub on GAZEBO, because my configuration is kinda messed up (I was updating my Ubuntu version).

At the time I could only test the movement with Vizzy's simulator. Everything looks like its working just fine (with one exception, but I think it is due to ROS stuff, so it should work fine with the iCub demo, otherwise I will explain what the problem is).

**Comment by traversaro** [comment]
Ok, I will test! In the mean while I think we can open the pull request so I can comment in line in your code the missing pieces.

**Comment by mikearagao** [comment]
Ok, just let me clean it before that.

**Comment by mikearagao** [comment]
@traversaro I saw the pull request you opened (a long time ago I know - will take care of it tomorrow I hope) but did you tested the code with demos you told me you have?

**Comment by traversaro** [comment]
Sorry I didn't I waited for the clean up you mentione in the previous comment! 
Totally unrelated, do you have any image of the Vizzy working in simulation?

**Comment by mikearagao** [comment]
Ok, I'll clean it now. I can get some images, do you need any specific set up?

**Comment by traversaro** [comment]
Nothing in particular, just an image of robot in the simulator is ok,
thanks a lot!
