### ISSUE TITLE
[Gazebo5] Test gazebo-yarp-plugins with Gazebo5

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#171]
Gazebo5 have been released yesterday. In these release there are several things that could bring incompatibility (for example C++11), we should have to test `gazebo-yarp-plugins`. I cannot test Gazebo5 in Travis because it is not supported on Ubuntu 12.04, so anyone is willing to test it and report any issue? 

Subtasks:
* [x] Test gazebo-yarp-plugins with Gazebo 5 on Ubuntu 
* [x] Test gazebo-yarp-plugins with Gazebo 5 on OS X

**Comment by EnricoMingo** [comment]
Hi, I have done some tests using Gazebo 5 and considering a "normal" usage,
it is working (ubuntu 14.04).

2015-01-28 9:58 GMT+01:00 Silvio Traversaro <notifications@github.com>:

> Gazebo5 have been released yesterday. In these release there are several
> things that could bring incompatibility (for example C++11), we should have
> to test gazebo-yarp-plugins. I cannot test Gazebo5 in Travis because it
> is not supported on Ubuntu 12.04, so anyone is willing to test it and
> report any issue?
>
> Subtasks:
>
>    -  Test gazebo-yarp-plugins with Gazebo 5 on Ubuntu
>    -  Test gazebo-yarp-plugins with Gazebo 5 on OS X
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotology/gazebo-yarp-plugins/issues/171>.
>



-- 
Ing. Mingo Enrico Hoffman
Istituto Italiano di Tecnologia, Genova

**Comment by traversaro** [comment]
Perfect!

**Comment by francesco-romano** [comment]
OS X:
- Successfully installed (yeah!)
- FT sensors ports are present
- Motor test works until joint 6 (tests are not correctly configured for gazebo)
- ?

**Comment by traversaro** [comment]
Fine for me.
