### ISSUE TITLE
Add Vizzy to gazebo-yarp-plugins usage examples

### ISSUE THREAD

**Issue by mikearagao** [robotology/gazebo-yarp-plugins#179]
Hi @traversaro ! Vizzy repo is now clean and ready to accept issues and regular users.

I know this took a little more than I expected but I guess this could be another example for the gazebo-yarp-plugins usage.

The repo is this one: https://github.com/vislab-tecnico-lisboa/vizzy.

Please feel free to ask for anything (photos, info, etc.). Testing and issuing are more than welcome of course (to be able to improve it is what we want after all) :smile: 

Cheers!

PS: maybe I should tag someone else, please point me who should I speak to.

**Comment by traversaro** [comment]
Thanks, link added in the readme!
