### ISSUE TITLE
Applying twice the same external wrench seems not to have effect

### ISSUE THREAD

**Issue by iron76** [robotology/gazebo-yarp-plugins#209]
At least in my operative system (MacOS) it seems that applying the very same external wrench on the very same link via the RPC connection `yarp rpc /icubGazeboSim/applyExternalWrench/rpc:i` does not have any effect after the first call.

**Comment by jeljaik** [comment]
Fixed in 0b4a645b835d0b19d6f631ab7be0ed2403b13436
Please check it out.
