### ISSUE TITLE
Provide a GazeboYARPPluginsConfig.cmake file 

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#212]
Necessary for:
- software using the thrift interface to pause/stop simulation such as https://github.com/robotology-playground/WBI-Toolbox .
- project that want to use the functions that simplify writing YARP devices that are opened by gazebo plugins, such as https://github.com/robotology/cer 

It should be easy to do this by importing the [`InstallBasicPackageFile`](https://github.com/robotology/ycm/blob/master/modules/InstallBasicPackageFiles.cmake) macro from YCM. 

We will then need to raise the CMake minimum required version to 2.8.11 , but I don't think that is a big issue. 

I don't particularly like the `GazeboYARPPlugins`, but I would go for it for compatibility with the Walkman superbuild.

**Comment by barbalberto** [comment]
:+1:

**Comment by traversaro** [comment]
cc @diegoferigo It can be done by following https://github.com/robotology/how-to-export-cpp-library/ .
