### ISSUE TITLE
gazebo 7 crash with depthCamera plugin

### ISSUE THREAD

**Issue by randaz81** [robotology/gazebo-yarp-plugins#225]
I just noticed that Gazebo 7 crashes if my sdf contains:

```<plugin name='depth_camera_plugin' filename='libgazebo_yarp_depthCamera.so'>
 <yarpConfigurationFile>model://cer/conf/gazebo_cer_depthCamera.ini</yarpConfigurationFile>
 </plugin>```

**Comment by traversaro** [comment]
Replicated also on OS X.

**Comment by traversaro** [comment]
@barbalberto any idea?

**Comment by barbalberto** [comment]
Gazebo7 has deprecated a lot of depthCamera functions... maybe it is one of them.
I had not time to test yet

**Comment by barbalberto** [comment]
Commited a fix on the branch fix_gazebo7

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/gazebo-yarp-plugins/pull/232 .
