### ISSUE TITLE
Controlboard regression

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#229]
@naveenoid  have reported some strange behaviours (joint reaching their limits on startup) with the new minimum jerk trajectory generator. While we investigate this we can switch back the default trajectory generator to the constant velocity one.

**Comment by naveenoid** [comment]
:+1:

**Comment by traversaro** [comment]
Everything seems to work fine at https://github.com/robotology/gazebo-yarp-plugins/commit/605f4292b47751dfac46dfd1dfb943876798e1b9 .

**Comment by randaz81** [comment]
Issue fixed in master (missing initial speed value?)
