### ISSUE TITLE
Gazebo crashed after removing iCub

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/gazebo-yarp-plugins#248]
`***** Internal Program Error - assertion (diffTime.sec < maxSensorUpdate) failed in void gazebo::sensors::SensorManager::SensorContainer::RunLoop(): /var/lib/jenkins/workspace/gazebo7-debbuilder/build/gazebo-7.2.0/gazebo/sensors/SensorManager.cc(551): Took over 1000*max_step_size to update a sensor.`

This error appeared on the terminal after the crash.
I noticed it happens often when I remove the robot.

**Comment by traversaro** [comment]
Relevant line in Gazebo source code : https://bitbucket.org/osrf/gazebo/src/5adf274c0172e4707ac86523c3aedd3d332f3c7c/gazebo/sensors/SensorManager.cc?at=default&fileviewer=file-view-default#SensorManager.cc-551 .

**Comment by Tobias-Fischer** [comment]
Can you try whether this still happens after applying https://github.com/robotology/gazebo-yarp-plugins/pull/253 and https://github.com/robotology/gazebo-yarp-plugins/pull/252 and https://github.com/robotology/yarp/pull/814 (with the latter not being merged yet!)?

**Comment by traversaro** [comment]
We don't know how to reproduce this issue, so let's wait one month if it does not happen anymore and then we can close the issue.

**Comment by traversaro** [comment]
@S-Dafarra Please update (and reopen) this issue if you experience this problem again.
