### ISSUE TITLE
Compilation problem with GCC, OpenCV on the VVV virtual machine

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#271]

**Comment by traversaro** [comment]
I totally forgot what this issue is about. @francesco-romano ?

**Comment by francesco-romano** [comment]
If I remember correctly one of the plugins was in conflict with iCub installed with opencv. Or something similar.

**Comment by traversaro** [comment]
Closing, if the problem arises again we will fix it.
