### ISSUE TITLE
World interface plugin

### ISSUE THREAD

**Issue by charleswilmot** [robotology/gazebo-yarp-plugins#273]
Hello,

I would like to use the `world` plugin but I've no idea what to start with.

Should I run `gazebo` with `-slibgazebo_yarp_worldinterface.so` ?
I don't have a `/world` port, is that normal?
How to add an object in the virtual environment?

Thank you very much,
Charles

**Comment by pattacini** [comment]
Duplicate of https://github.com/robotology/QA/issues/201
