### ISSUE TITLE
Gazebo 8 - ignition 

### ISSUE THREAD

**Issue by iron76** [robotology/gazebo-yarp-plugins#277]
When compiling I am getting the following error:

``` gazebo-yarp-plugins/plugins/depthCamera/src/DepthCameraDriver.cpp:19:10: fatal  error:  'ignition/math2/ignition/math/Angle.hh' file not found```

Apparently in my installation I have `ignition/math3/ignition/math/Angle.hh`.

**Comment by traversaro** [comment]
Can you paste the output of : `brew list` and the content of the `CMakeCache.txt` present in the build of `gazebo-yarp-plugins`?

**Comment by traversaro** [comment]
PR https://github.com/robotology/gazebo-yarp-plugins/pull/278 should fix the issue.

**Comment by traversaro** [comment]
This was indirectly caused by https://github.com/robotology/gazebo-yarp-plugins/issues/275 .

**Comment by iron76** [comment]
Sure. Here they are.

[CMakeCache.txt](https://github.com/robotology/gazebo-yarp-plugins/files/752133/CMakeCache.txt)
[brew_list.txt](https://github.com/robotology/gazebo-yarp-plugins/files/752134/brew_list.txt)

**Comment by traversaro** [comment]
@iron76 The issue should have been solved by https://github.com/robotology/gazebo-yarp-plugins/pull/278 .

**Comment by traversaro** [comment]
This was solved by https://github.com/robotology/gazebo-yarp-plugins/pull/278 , please re-open if the problem persists.
