### ISSUE TITLE
Devel travis build always failing

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#297]
I guess this is due to the fact that the devel branch is using yarp master. 
@diegoferigo can you check this? Thanks

**Comment by diegoferigo** [comment]
No, Travis uses `yarp:devel` on branches different than `master`. I guess the issue here is that the docker image with `yarp:devel` is not very updated, since its regeneration is performed manually. Let's wait dockerhub rebuilding it, I will follow up on this.

**Comment by diegoferigo** [comment]
Due to a long chain of dependencies, this issue will be fixed as soon as https://github.com/robotology/yarp/pull/1194 is merged in `yarp:devel`.

**Comment by diegoferigo** [comment]
The PR has been merged in `yarp:devel`, and the last commits in [robotology/docker_images](https://github.com/robotology-playground/docker_images) fix this issue.

**Comment by traversaro** [comment]
👍
