### ISSUE TITLE
"Not removing device ...  yet because it is still used by other devices, Decremented counter to  1" error

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#323]
This message: https://github.com/robotology/gazebo-yarp-plugins/blob/8929c45e6fcdedb32d06e9e641604699770c6c75/libraries/singleton/src/Handler.cc#L211 is not an error, and should not be printed at all, as it is part of the expected behaviour of singleton `Handler` class.  

cc @barbalberto Any objection to its removal?

**Comment by barbalberto** [comment]
You are absolutely right! It has to be removed
