### ISSUE TITLE
Possibile memory leaks

### ISSUE THREAD

**Issue by triccyx** [robotology/gazebo-yarp-plugins#328]
In file ControlBoardDriver.cpp check the following lines:

line 844
yarp::dev::Pid* yarpPid;
yarpPid = new yarp::dev::Pid[m_numberOfJoints];

line 992
yarp::dev::Pid* yarpPid;
yarpPid = new yarp::dev::Pid[m_numberOfJoints];

line 1084
double* stiffness;
double* damping;
stiffness = new double[m_numberOfJoints];
damping   = new double[m_numberOfJoints];

Thanks to cppcheck

**Comment by traversaro** [comment]
Will be fixed by https://github.com/robotology/gazebo-yarp-plugins/pull/324 .

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/gazebo-yarp-plugins/pull/324 .
