### ISSUE TITLE
Remove hardcoded parameters in controlboard plugin

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#332]
There are a few hardcoded parameters in the controlboard plugin, including:
* The `maxTorques` vector, used to decide when the joint goes in hardware fault mode, hardcoded to 2000 ( https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/controlboard/src/ControlBoardDriver.cpp#L69 , see https://github.com/robotology/gazebo-yarp-plugins/issues/331  )

* There are also the parameters:
~~~
const double RobotPositionTolerance_revolute = 0.9;      // Degrees
const double RobotPositionTolerance_linear = 0.004; // Meters
~~~
but with a preliminary check it seems to be that those values are unused. In that case they can be directly removed.

**Comment by triccyx** [comment]
What is the correct section of *.ini to put  maxTorques ?

**Comment by triccyx** [comment]
const double RobotPositionTolerance_revolute = 0.9;      // Degrees
const double RobotPositionTolerance_linear = 0.004; // Meters

are used in:


bool GazeboYarpControlBoardDriver::configureJointType()

**Comment by traversaro** [comment]
> What is the correct section of *.ini to put maxTorques ? 

I would go in the generic section, similar to what we do for `min_damping` and `min_stiffness` : 
https://github.com/robotology/icub-gazebo/blob/master/icub/conf/gazebo_icub_left_leg.ini#L32
(even if this one should be eventually moved in `IMPEDANCE_CONTROL` . : )

> bool GazeboYarpControlBoardDriver::configureJointType() 

Great, then we should add parameters in the configuration file also for them.

**Comment by triccyx** [comment]
What should be the policy if a param is wrong/bad formatted?
keep on analyze the next params?

**Comment by traversaro** [comment]
In general I would fail early to make sure that the wrong parameter is properly noted by the model author. In particular in this context I would keep the code consistent with the rest of the plugin, and return false in the `gazebo_init` function.

**Comment by triccyx** [comment]
Ok, I ask this because the gazebo_init has some return false, but sometimes the submethods are always true see for example setMinMaxImpedance.
For the new ones I'll follow your suggestion
