### ISSUE TITLE
Access to state of links and models in Gazebo

### ISSUE THREAD

**Issue by xEnVrE** [robotology/gazebo-yarp-plugins#337]
It seems that none of the plugins available in `gazebo-yarp-plugins` allows to access to the state of the links and models loaded inside Gazebo. While for links one could have developed its own plugin providing the state of the links of a robot it could be useful to have access to the state of the models loaded inside Gazebo. This way one could get the position and the orientation of objects that the robot is interacting with and, for example, compare it with an estimate provided by a localization algorithm.

This feature is implemented in `gazebo_ros` for example ([link](http://gazebosim.org/tutorials/?tut=ros_comm#GazeboPublishedTopics)) with topics providing the state of all the links and all the models.

Among the plugins available in `gazebo-yarp-plugins` the plugin `gazebo_yarp_worldinterface` offers a __Thrift__ based API that allows to create standard objects, move them, get their pose and so on. Could it be an option to add a method that allows the user to access to the state of a model loaded inside Gazebo but not created using the plugin, e.g. loaded using a `.sdf` file?

Since sending the state of all the models on a port seems an overkill other solutions may be proposed:

- a method like
```
Pose getModelPose(model_name)
```
where `model_name` is the name of the model within Gazebo, returning the current pose of the model 
- a method like
```
bool requestModelPose(model_name, port_name, send_rate)
```
After calling this method the plugin should start sending the state of the model with name `model_name` over the port `port_name` with a given rate `send_rate`.

It would be great to know your opinions about this!

**Comment by traversaro** [comment]
I like the idea, and I think the use case is clear. 
Some brainstorming (don't take this comment as gospel please : ) ) :
Some comments on the proposed design: 
* You are proposing to add a method to open a port that publishes data. Do you think you should also have a method to close the port? 
* The `gazebo_yarp_worldinterface` plugin is already quite complicated, so perhaps it could make sense to implement this in a separate plugin. What to do think?

Some possible alternative designs to achieve the same use case:
* Instead of publishing each model information in its own port, you could publish all the model poses in one port/topic, similar to what the ros plugins does. Drawbacks: in complex simulation scenario, the amount of data published on that port could be big. 
* Instead of publishing model information on a separate port/topic, this information could be published in the tf system, using the `FrameTransformServer` and `FrameTransformClient` devices (https://github.com/robotology/yarp/tree/9a395f6e41e01d8d350b6a4e5e2b2f6c6f913b74/src/libYARP_dev/src/devices/FrameTransformClient and https://github.com/robotology/yarp/tree/1162533d024ca66b7658b44e434b67df2ea16f29/src/libYARP_dev/src/devices/FrameTransformServer). Drawbacks of this solution: you will need the `FrameTransformServer`  up whenever you want to run the plugin, the TF system in YARP is not document, and you would not access the velocities of the models.

**Comment by xEnVrE** [comment]
I agree with you as regards the plugin `gazebo_yarp_worldinterface`. Also this feature may not fit so well in the interface of that plugin that is designed as an interface to handle objects that are created with that plugin.

Since velocities could be useful and since publishing all the models seems to me exaggerated, sometimes you do not need the state of every object in the scenario, another solution could be that of implementing this feature in a `model` plugin. The user could insert that in the sdf of the model and when the object is inserted in the environment the plugins publishes the state of the object over a port.

The name of the port can be obtained by composing a prefix given by the user, .e.g. inside a `.ini` linked in the `.sdf`,  with the name of the model obtained internally from Gazebo (this way multiple objects of the __same type__ added to the environment can be handled easily).

**Comment by traversaro** [comment]
> Since velocities could be useful and since publishing all the models seems to me exaggerated, sometimes you do not need the state of every object in the scenario, another solution could be that of implementing this feature in a model plugin. The user could insert that in the .sdf of the model and when the object is inserted in the environment the plugin publishes the state of the object over a port.

I agree (please make sure that this fits well with your user case : ) ). 

> The name of the port can be obtained by composing a prefix given by the user, .e.g. inside a .ini linked in the .sdf, with the name of the model obtained internally from Gazebo (this way multiple objects of the same type added to the environment can be handled easily). 

Two comments on this:
* It may be worth to make sure that plugin could handle well also the case of two models of the same kind nested in two different composite models. 
* Requiring a `.ini` file for each plugin was an historical choice, but I think it proveed to be an unnecessary complexity for simple plugins. See https://github.com/robotology/gazebo-yarp-plugins/issues/142 or evaluate the possibility of directly get the settings directly from SDF.

**Comment by xEnVrE** [comment]
>I agree (please make sure that this fits well with your user case : ) ).

It fits well, better than the solution with `gazebo_yarp_worldinterface` : )

>Two comments on this:
-It may be worth to make sure that plugin could handle well also the case of two models of the same kind nested in two different composite models.

I don't know how the naming behaves in case of nested models in Gazebo but I will make some trials to understand it.

>-Requiring a .ini file for each plugin was an historical choice, but I think it proveed to be an unnecessary complexity for simple plugins. See #142 or evaluate the possibility of directly get the settings directly from SDF.
This seems a more straightforward way to get parameters from the SDF. I will certainly take it into account.

**Comment by Yeshasvitvs** [comment]
@traversaro I wrote a small plugin called [accesslinkpose](https://github.com/Yeshasvitvs/gazebo-yarp-plugins/tree/topology_estimation_plugins/plugins/accesslinkpose) to send the pose of specific links given in a config file as the following example

```
[include "gazebo_1r_2link_robotname.ini"]

port_name /${gazeboYarpPluginsRobotName}/pose_output:o
number_of_links 2
link_names first_link second_link
link_pose_type world world
```

This may be useful.

**Comment by prashanthr05** [comment]
@xEnVrE @Yeshasvitvs  Guys, in your experience, could your versions be expanded to portray a ground truth sensor plugin exposing the pose and velocities of desired link with respect to the gazebo world frame, considering the discussions in https://github.com/robotology/yarp/issues/1526 ? 

@traversaro do you see a sense if this existed as a ground truth sensor in the new sensor architecture?

**Comment by xEnVrE** [comment]
@prashanthr05 I think that the expansion is possible. The major concern is that we should find a standard way to represent and expose pose and velocity to the user. Now I'm using the `yarp::dev::FrameTransformClient`, together with a `yarp::dev::FrameTransformServer`, to publish a pose on the server. Also `yarp::math::FrameTransform` is available to extract translation and rotation from the transformation matrix coming from the client.

However there are no standard way to represent velocities, i.e. something implementing the concept of a `twist`. A ground truth sensor could be an idea.

**Comment by prashanthr05** [comment]
On top of exposing the `yarp::dev::FrameTransformClient` talking to `yarp::dev::FrameTransformServer` which just handles the pose related information, what if we used something like the proposed `MultipleAnalogSensorsClient` talking to the `MultipleAnalogSensorsServer` to send the pose + velocity information through a YARP port ?

**Comment by xEnVrE** [comment]
I like the idea but, as you said, we should ask if it make sense to consider such a ground truth sensor within the AnalogSensor architecture. 

Since explicit support for `pose`s and `twist`s within YARP seems not to exist another solution cold be that of implementing two `yarp::os::portable`, one for `pose` and for `twist`, and then send data using YARP ports.

**Comment by prashanthr05** [comment]
@traversaro  Could you provide some insight on this ?

**Comment by prashanthr05** [comment]
@xEnVrE  @Yeshasvitvs Guys, with the help of your plugins, I just wrote yet another redundant code (yarc :P) to get the pose and velocity of desired links through a yarp analogSensor device (I could have reused your versions, I really wanted to, but it didn't fully cover my requirements, so I did this. I apologize for it, however, my version is fully inspired from both of yours) The aim was to obtain a serialization of the data something like (link1_name x y z r p y linvel angvel)  (link2 .......) (.....) , but which I realized is not possible with the current version of the analog sensor interface.  Right now I'm just passing it as a continuous series of 12 state variables for each link over a port, so it makes us necessary for us to know the sequence of links at any point of use. This serialization is bad, but at the moment, fulfils my requirement. 

I request you to take a look at the code. I am not going to make a PR on it. But however, if you could take a look at it and discuss how we can change towards a better design to incorporate a analog sensor exposing the data on ports and a frame transform interface exposing the transforms for other processes to use, at the same moment, it would be great. 

https://github.com/prashanthr05/gazebo-yarp-plugins/tree/feature/groundtruthsensor/plugins/groundtruth

**Comment by traversaro** [comment]
Sorry guys, I totally forgot to reply to this issue. 

The initial idea for the `MultipleAnalogSensors` proposal was to wrap physical sensors**ᵃ** that actually exist in the real world. 

As we have already in the `MultipleAnalogSensors`  the interfaces for orientation measurements (IMU) and angular velocity measurements (gyroscope) to support @prashanthr05 idea we would need to add interfaces for getting the linear position of a body-fixed frame w.r.t. to an external frame, and for getting the linear velocity of a body-fixed frame w.r.t. to an external frame.

While devices that return measurements of this quantity may exists under some conditions  in the real world (LIDAR and a known fixed map for the linear position, Doppler Velocity Logs for the linear velocity for water vehicles) I am afraid that this would be **bitting off more than we can chew** (in italian: **fare il passo piu' lungo della gamba**) at least at this stage, so I would prefer to avoid this, at least unless the `MultipleAnalogSensors` proposal have been merge in YARP. 

**ᵃ**Note that I use "sensors" in an extended sense, i.e. IMU are considered as orientation sensors  even if their output is obtained as the output of an estimation process

**Comment by traversaro** [comment]
Given that a plugin by @xEnVrE was successfully merged in the repo, I think we can close the issue.

Just a small comment: I see a common pattern in your workflow @xEnVrE , @Yeshasvitvs  and @prashanthr05 : your private code depends on application-specific plugins added in a **fork** of gazebo-yarp-plugins. While this is ok for your private use, it may complicate deployment of your code (i.e. if one of your supervisors want to check your code/experiments). 

Even if you are eventually planning to contribute your plugin to gazebo-yarp-plugins  I think it make much more sense to **keep this plugins** in your own repo (perhaps the same repo that contains the code of your experiments), that should not be fork of **gazebo-yarp-plugins**. If you need to use any library/header/cmake macro present in **gazebo-yarp-plugins**, we can easily modify gyp to **gazebo-yarp-plugins** to install these files, and then your code can depend on it using a standard `find_package(GazeboYARPPlugins REQUIRED)` CMake command.
