### ISSUE TITLE
Reset Gazebo simulation

### ISSUE THREAD

**Issue by triccyx** [robotology/gazebo-yarp-plugins#344]
About testing purpose. It could be useful to reset Gazebo simulation from rpc call.

**Comment by traversaro** [comment]
This could be useful also for RL training @diegoferigo .

**Comment by diegoferigo** [comment]
This would be awesome for RL!

The only issue I see here with our current iCub infrastructure is that sometimes modules running on the simulated robot put the robot in a state such that the reset is not enough, and removing / re-dropping the model in the world is necessary. However, this is not directly related to `gazebo-yarp-plugins`.

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/gazebo-yarp-plugins/pull/345 .
