### ISSUE TITLE
Travis broken on devel 

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#357]
See https://github.com/robotology/gazebo-yarp-plugins/pull/356#issuecomment-391994934

**Comment by traversaro** [comment]
Blocked by https://github.com/robotology-playground/docker_images .

**Comment by diegoferigo** [comment]
Fixed by https://github.com/robotology-playground/docker_images/commit/f1b839b9306a2449966abf101ce56abc5eaaccc7
