### ISSUE TITLE
Update gazebo-yarp-plugins in devel after merging of YARP PR 1704 

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#361]
See https://github.com/robotology/yarp/pull/1704 for more info.

**Comment by jeljaik** [comment]
Opened pull request:
https://github.com/robotology/gazebo-yarp-plugins/pull/362

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/gazebo-yarp-plugins/pull/362 .
