### ISSUE TITLE
Wrong implementation of  yarp::dev::IPositionControl::checkMotionDone in Control board plugin

### ISSUE THREAD

**Issue by xEnVrE** [robotology/gazebo-yarp-plugins#377]
It seems that the implementation of the method
`
yarp::dev::IPositionControl::checkMotionDone (const int n_joint, const int * joints, bool * flags)
`
within the control board plugin is wrong.

According to the [documentation](http://www.yarp.it/classyarp_1_1dev_1_1IPositionControl.html#a78e3171536e8a6f0705435f9d3baf769) `flags` is a pointer to the return value that should be the logical "and" of all set of joints. However the code

https://github.com/robotology/gazebo-yarp-plugins/blob/3fa2c45a4b8a63ef15c524462124b505f29b3ed9/plugins/controlboard/src/ControlBoardDriverPositionControl.cpp#L235

tries to write into the variable `flags` as it was an array of booleans resulting in a

```
*** stack smashing detected ***: gzserver terminated
```

when the pointer to a single boolean is given to the function.

**Comment by traversaro** [comment]
Good catch. I am a bit unable to tackle this in the next days, but PR are welcome.

**Comment by xEnVrE** [comment]
@traversaro I'm planning to do this very soon!

**Comment by xEnVrE** [comment]
Sorry for the huge delay. I am addressing this in the PR #416.
