### ISSUE TITLE
Investigate support for "Modern" Gazebo Sim

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#395]
Citing [Gazebo March  2019 Blog Post](http://gazebosim.org/blog/acropolis):

>   The latest release of Gazebo, Gazebo 10, was rolled out in January 2019. We plan to continue to support Gazebo over the coming year and release Gazebo 11 in 2020. Gazebo 11 will be an LTS release, with a EOL date of Jan 2025. Gazebo 11 will also the be final release of the Gazebo lineage. Development efforts toward simulation will focus primarily on Ignition. Users of Gazebo can expect migration guides, tutorials, and additional help to be developed over the course of 2019 and 2020 to aid in the transition.
> 
> Over 16 years of experience has helped to inform and guide the development of Ignition. We believe that the shift toward Ignition will be extremely beneficial to community. As always, this remains an open-source project and we look forward to your feedback and contributions. 

The first released version of Ignition Gazebo 11 came out in March 2019, and it is currently under development in https://github.com/ignitionrobotics/ign-gazebo, under the name of "Ignition Gazebo". Despite the simulator goes by "Gazebo" name, it is basically a complete rewrite of the Gazebo simulator, using a [Entity–component–system](https://en.wikipedia.org/wiki/Entity%E2%80%93component%E2%80%93system) pattern. As the Gazebo Classic plugin API is basically the complete Gazebo C++ API, the `gazebo-yarp-plugins` plugins will need to be adapted to run simulations with YARP-enabled models on the new Ignition Gazebo. I open this issue to start collecting ideas and resources related to this migrations. 

## Docs on Ignition Gazebo Architecture
* Architecture Document on Ignition Gazebo: https://github.com/ignitionrobotics/docs/blob/804909e6351ae679a022042570eb0b7bdc550988/architecture.md 
* Tutorial  on Implementing a System Plugin in Ignition Gazebo (not to be confused with System plugins in Gazebo Classic): https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/tutorials/create_system_plugins.md 

## General Brainstorming
* As all big software  migrations, I fear this one will be long and for several years we will need to have plugins working for Gazebo Classic. For this reason I think the repo should be able to compile plugins for both Gazebo Classic and Ignition Gazebo out of the same branch and out of the same build directory. 
Fortunately all different major versions of Ignition Libraries are  parallel installable, and also Gazebo Classic and Ignition Gazebo will be installable in parallel.  So this  should be doable.
* The amount of code  and logic contained in some plugins (for example the controlboard plugin) is huge and complex. I think the right strategy is try to share as much as possible that code between Gazebo Classic  driver/plugins and Ignition Gazebo driver/plugins.

**Comment by traversaro** [comment]
Relevant ign-gazebo design PR: https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/98/design-doc-beginning-of-plugin-interface/diff .

**Comment by traversaro** [comment]
Renamed issue as apparently Gazebo 11 will still be the "old" gazebo, and the "new" Gazebo will be Ignition Gazebo (1|2|3|..).

**Comment by traversaro** [comment]
Related issue: https://bitbucket.org/ignitionrobotics/ign-gazebo/issues/35/tutorial-on-how-to-transition-from-gazebo9 .

**Comment by traversaro** [comment]
Nice tutorial on how to migrate a plugin from Gazebo Classic to Ignition Gazebo: https://github.com/ignitionrobotics/ign-gazebo/pull/80 .

**Comment by diegoferigo** [comment]
https://github.com/ignitionrobotics/ign-gazebo/issues/325 collects upstream contributions providing high-level APIs that could help the migration

**Comment by traversaro** [comment]
Changed the title of the issue now that "Ignition Gazebo"  is "Gazebo Sim", see https://community.gazebosim.org/t/a-new-era-for-gazebo/1356 .

**Comment by traversaro** [comment]
This is also an interesting tutorial: https://gazebosim.org/api/sim/7/ardupilot.html . cc @GiacomoBisio @lucapa17

**Comment by traversaro** [comment]
All work on this is ongoing at https://github.com/robotology/gz-sim-yarp-plugins, closing this issue as it does not make sense to track anything here. fyi @xela-95
