### ISSUE TITLE
Linking on gazebo_yarp_externalWrench plugin is broken on devel

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#420]
In https://github.com/robotology/gazebo-yarp-plugins/pull/418, the `GazeboYarpPlugins::hasEnding` function contained in the `gazebo_yarp_lib_common` library is used in gazebo_yarp_externalWrench plugin is used, but the corresponding library is not linked in the `CMakeLists.txt`'s of the plugin. Depending on the os and build generator system this can create include or linking problems. 

@Yeshasvitvs can you fix this? Thanks!

**Comment by Yeshasvitvs** [comment]
@traversaro fixed it in https://github.com/robotology/gazebo-yarp-plugins/pull/422

**Comment by Yeshasvitvs** [comment]
@traversaro we still keep this issue open right ?

**Comment by traversaro** [comment]
If the fix was merged in master or in devel, then we close it.
