### ISSUE TITLE
Add Continuos Integration on macOS

### ISSUE THREAD

**Issue by kouroshD** [robotology/gazebo-yarp-plugins#444]
Currently, in the `~.travis.yml`, there is only test for Linux machine. We should the test for the macOS as well.

Related comment: https://github.com/robotology/gazebo-yarp-plugins/issues/428#issuecomment-499431927

**Comment by traversaro** [comment]
This was fixed by https://github.com/robotology/gazebo-yarp-plugins/pull/453 .
