### ISSUE TITLE
why can not ft sensor connect to fixed joint in gazebo?

### ISSUE THREAD

**Issue by kamilcetin** [robotology/gazebo-yarp-plugins#480]
Hi Silvio,

In your comment in the issue (Full support for 6-axis Force/Torque sensor simulation #73), you said that: Another (not as big as the first one) issue is that for simulating a F/T sensor embedded in a link it is necessary to insert a fixed joint in the description of the robot. However fixed joint are not currently supported in the SDF format...

In my gazebo model, I attached a ft sensor at the end-effector of a 7dof robot manipulator. If the ft sensor is fixed joint, there is no rostopic about force data. If I make it revolute joint I can read force data, but total joint size of robot become 8, and it makes sizematch problems later. Why can not ft sensor connect to fixed joint in gazebo?

Cioa,
Kamil.

**Comment by traversaro** [comment]
Hi @kamilcetin, 
   if you have a question of how to use a `gazebo_ros_plugins`, I suggest to open an issue on ROS Answers (https://answers.ros.org/questions/) with specific details on the problem you are facing and your configuration (which ROS plugin are you using? what exact code are you using in your URDF or SDF file to add the FT sensors). In any case, if you are using a fixed joint with a URDF I suggest you to use the `preserveFixedJoints` tag,  as discussed in https://answers.gazebosim.org//question/21118/converting-urdf-to-sdf-preservefixedjoint-not-working/ . Furthermore, also this docs of Gazebo can be interesting: http://gazebosim.org/tutorials?tut=force_torque_sensor&cat=sensors .

Given that you request is not related at all with this repo I will close this issue, but if  instead you have a question or problem related to `gazebo-yarp-plugins`, feel free to open a new issue, thanks!
