### ISSUE TITLE
Documentation site down?

### ISSUE THREAD

**Issue by maxymczech** [robotology/gazebo-yarp-plugins#538]
http://robotology.gitlab.io/docs/gazebo-yarp-plugins/master/

The page return error code 404.

**Comment by traversaro** [comment]
Thanks @maxymczech ! Indeed this is a known issue and tracked in https://github.com/robotology/gazebo-yarp-plugins/issues/487 . I would close this issue as a duplicate, thanks in any case for reporting the issue!
