### ISSUE TITLE
Implement interface to control PID gain values

### ISSUE THREAD

**Issue by francesco-romano** [robotology/gazebo-yarp-plugins#60]
We must implement the PID interface (or how it is named in yarp), so the pid gain values are exposed also on the robotMotorGui

@barbalberto

**Comment by traversaro** [comment]
For implementing `IPidControl` you have to implement the functions for which we now just have a stub returning `false` here: https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/controlboard/src/ControlBoardDriverPidControl.cpp . 

For seeing how the PID gains are loaded at plugin startup (to get an idea how they can be modified on the fly), you can check the `setPIDsForGroup` method at `https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/controlboard/src/ControlBoardDriver.cpp#L256`.

**Comment by traversaro** [comment]
If we implement this interfaces, we should check the unit of measurement that we are assuming for the gains (see https://github.com/robotology/gazebo-yarp-plugins/issues/119 ).
