### ISSUE TITLE
Virtual Crane / Initial Configuration plugin

### ISSUE THREAD

**Issue by arocchi** [robotology/gazebo-yarp-plugins#67]
It would be useful to have a way to specify an initial configuration for the robot in a particular .world file, or eventually have the possibility to disable gravity and raise the robot in order to simulate the use of a crane, when the robot is supposed to reach the desired homing position

**Comment by traversaro** [comment]
An harness plugin has been added in Gazebo : 
* http://gazebosim.org/blog/newsletter_3
* https://bitbucket.org/osrf/gazebo/pull-requests/2346
