### ISSUE TITLE
Proper (e.g. minJerk) trajectory generation should be implemented

### ISSUE THREAD

**Issue by iron76** [robotology/gazebo-yarp-plugins#68]
There was a bug in the trajectory generation such that the robot was getting stuck in a configuration without reaching the desired final posture. A workaround was to increase the velocity. I just fixed this bug, however we are still missing a proper trajectory generator. At the moment the trajectory generator is just a linear interpolator with constant velocity (as configured with the setRefSpeed or setRefSpeeds). A proper trajectory generator should be added, e.g. the minimum jerk trajectory.

**Comment by randaz81** [comment]
I'm going to take care of this

**Comment by randaz81** [comment]
Minimum jerk trajectory generator complete.
