### ISSUE TITLE
Migrate all the printf/cout to gazebo defined macros

### ISSUE THREAD

**Issue by francesco-romano** [robotology/gazebo-yarp-plugins#87]
Instead of using `printf` or `cout` we should use gazebo defined output functions

Gazebo defines the following loggers:
- `gzdbg`
- `gzerr`
- `gzwarn`

They are defined in `common`: `gazebo/common/Console.hh`

**Comment by traversaro** [comment]
Even for yarp output that is not directly sent to gazebo streams (such as information on port opened, file searched by resource finder) we should enable/disable the verbosity using the [`Console::GetQuiet()`](https://osrf-distributions.s3.amazonaws.com/gazebo/api/dev/classgazebo_1_1common_1_1Console.html#a1240d0b06e31d05ee891e3880224c06f) method to get if Gazebo was launched with the `--verbose` option (typically used to understand when something is not working).

**Comment by traversaro** [comment]
Most of the prints moved to YARP logger in https://github.com/robotology/gazebo-yarp-plugins/pull/242 .
