### ISSUE TITLE
Gazebo Reset World causes unrealistic joint torques

### ISSUE THREAD

**Issue by iron76** [robotology/gazebo-yarp-plugins#92]
A "Reset World" action results in strange values for joint torques very different (~1e4) from the torques that the system gives at the first insertion of the model.

**Comment by traversaro** [comment]
We should add a callback on the World Reset event [1] to properly reset the controller state.
[1] https://bitbucket.org/osrf/gazebo/issue/1375/add-events-connectworldreset-and-events

**Comment by traversaro** [comment]
http://answers.gazebosim.org/question/8552/how-can-i-reset-the-simulation-properly-in-gazebo/ actually we should properly implement the Reset() method in the controlboard plugin.

**Comment by traversaro** [comment]
cc @barbalberto apparently we just need to write the `Reset()` method for the ControlBoard plugin .

**Comment by barbalberto** [comment]
Great @traversaro, thanks. I'll check it asap

**Comment by rlober** [comment]
Any news on this? Pingalingpingpingdingdong

**Comment by traversaro** [comment]
I drunkly promised to fix it, so I guess now I need to actually fix this. :D

**Comment by rlober** [comment]
Hahaha YES!!!!

**Comment by DanielePucci** [comment]
:D

**Comment by rlober** [comment]
Any news on this? @traversaro @iron76 @francesco-romano

**Comment by rlober** [comment]
@traversaro If you need some help on this just point @jeljaik and myself to the right file and we can try to figure it out. This is pretty critical for us so I am happy to volunteer some time to this problem, I just need to know where to start.

**Comment by traversaro** [comment]
Yes, sorry guys! 
My impression is that the Gazebo JointController is not properly resetted on World Reset. 
We then need to implemented the `Reset()` method in [`gazebo::GazeboYarpControlBoard`](https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/controlboard/src/ControlBoard.cc) and properly reset the controlboard logic and call the reset on the Gazebo JointController... the big problem that I know see is that the JointController pointers are all contained in the [`ControlBoardDriver`](https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/controlboard/include/yarp/dev/ControlBoardDriver.h) class, so it may more convenient to add a callback on the [`WorldReset`](https://bitbucket.org/osrf/gazebo/issues/1375/add-events-connectworldreset-and-events) event, as we already do for the `WorldUpdate` event.
