### ISSUE TITLE
Check unnecessary error messages in terminal

### ISSUE THREAD

**Issue by francesco-romano** [robotology/gazebo-yarp-plugins#98]
The new plugin continues to print error messages in the terminal (something like "Error could not find link ..").
We should avoid unnecessary errors, also because I am not interacting with the robot.

I think now is not the time to touch the plugin, because of the ICRA workshop, but after that I think @jeljaik can solve this issue (together with the code styling task).

**Comment by DanielePucci** [comment]
No longer replicable. Closing this issue.
