### ISSUE TITLE
libSingleton.so not found if installed

### ISSUE THREAD

**Issue by barbalberto** [robotology/gazebo-yarp-plugins#99]
if GAZEBO_PLUGIN_PATH point to the folder where plugins are installed, like:
   /usr/local/src/robot/walkman/build/install/lib/

when Gazebo starts it is able to find the plugin (libgazebo_yarp_forcetorque.so), but the plugin is not able to find the singleton library (libgazebo_yarp_singleton.so)

gibing the following error:

Error [Plugin.hh:141] Failed to load plugin /usr/local/src/robot/walkman/walkman/build/install/lib/libgazebo_yarp_forcetorque.so: libgazebo_yarp_singleton.so: cannot open shared object file: No such file or directory

If the GAZEBO_PLUGIN_PATH points to the build folder, like: 
    /usr/local/src/robot/walkman/build/external/GazeboYARPPlugins
everythings works fine.

**Comment by traversaro** [comment]
I think this have been fixed adding RPATH support, feel free to reopen if the issue persist.
